/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mediatek_tv_service_TVNative */

#ifndef _Included_com_mediatek_tv_service_TVNative
#define _Included_com_mediatek_tv_service_TVNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    openUARTSerial_native
 * Signature: (I[I[I)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_openUARTSerial_1native
  (JNIEnv *, jclass, jint, jintArray, jintArray);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    closeUARTSerial_native
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_closeUARTSerial_1native
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    getUARTSerialSetting_native
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_getUARTSerialSetting_1native
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    getUARTSerialOperationMode_native
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_getUARTSerialOperationMode_1native
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    setUARTSerialSetting_native
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_setUARTSerialSetting_1native
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    setUARTSerialOperationMode_native
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_setUARTSerialOperationMode_1native
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    setUARTSerialMagicString_native
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_setUARTSerialMagicString_1native
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    outputUARTSerial_native
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_outputUARTSerial_1native
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    autoAdjust_native
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_autoAdjust_1native
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    powerOff_native
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_powerOff_1native
  (JNIEnv *, jclass);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    getCfg_native
 * Signature: (ILjava/lang/String;Lcom/mediatek/tv/common/ConfigValue;Lcom/mediatek/tv/common/ConfigValue;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_getCfg_1native
  (JNIEnv *, jclass, jint, jstring, jobject, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    setCfg_native
 * Signature: (ILjava/lang/String;Lcom/mediatek/tv/common/ConfigValue;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_setCfg_1native
  (JNIEnv *, jclass, jint, jstring, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    updateCfg_native
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_updateCfg_1native
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    resetCfgGroup_native
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_resetCfgGroup_1native
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    getCfgMinMax_native
 * Signature: (Ljava/lang/String;Lcom/mediatek/tv/common/ConfigValue;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_getCfgMinMax_1native
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    readGPIO_native
 * Signature: (Lcom/mediatek/tv/common/ConfigValue;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_readGPIO_1native
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    writeGPIO_native
 * Signature: (Lcom/mediatek/tv/common/ConfigValue;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_writeGPIO_1native
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    channelSelect_native
 * Signature: (Lcom/mediatek/tv/model/ChannelInfo;Z)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_channelSelect_1native
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    channelSelectEx_native
 * Signature: (Lcom/mediatek/tv/model/ChannelInfo;Lcom/mediatek/tv/model/ExtraChannelInfo;ZII)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_channelSelectEx_1native
  (JNIEnv *, jclass, jobject, jobject, jboolean, jint, jint);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    syncStopService_native
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_syncStopService_1native
  (JNIEnv *, jclass);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    startVideoStream_native
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_startVideoStream_1native
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    syncStopSubtitleStream_native
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_syncStopSubtitleStream_1native
  (JNIEnv *, jclass);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    fineTune_native
 * Signature: (Lcom/mediatek/tv/model/ChannelInfo;IZ)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_fineTune_1native
  (JNIEnv *, jclass, jobject, jint, jboolean);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    freeze_native
 * Signature: (IZ)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_freeze_1native
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    setVideoMute_native
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_setVideoMute_1native
  (JNIEnv *, jclass);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    getVideoResolution_native
 * Signature: (ILcom/mediatek/tv/model/VideoResolution;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_getVideoResolution_1native
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    getAudioInfo_native
 * Signature: (ILcom/mediatek/tv/model/AudioInfo;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_getAudioInfo_1native
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    getSignalLevelInfo_native
 * Signature: (ILcom/mediatek/tv/model/SignalLevelInfo;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_getSignalLevelInfo_1native
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    getDtvAudioInfo_native
 * Signature: (Lcom/mediatek/tv/model/AudioLanguageInfo;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_getDtvAudioInfo_1native
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    setDtvAudioLang_native
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_setDtvAudioLang_1native
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    setDtvAudioLangByIndex_native
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_setDtvAudioLangByIndex_1native
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    getSubtitleInfo_native
 * Signature: (Lcom/mediatek/tv/model/SubtitleInfo;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_getSubtitleInfo_1native
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    setSubtitleLang_native
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_setSubtitleLang_1native
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    getStreamMpegPid_native
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_getStreamMpegPid_1native
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    selectMpegStreamByPid_native
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_selectMpegStreamByPid_1native
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    isCaptureLogo_native
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mediatek_tv_service_TVNative_isCaptureLogo_1native
  (JNIEnv *, jclass);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    setMute_native
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_setMute_1native
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    getMute_native
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mediatek_tv_service_TVNative_getMute_1native
  (JNIEnv *, jclass);
/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    getDtvAudioDecodeType_native
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_getDtvAudioDecodeType_1native
  (JNIEnv *, jclass);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    setVideoBlueMute_native
 * Signature: (IZZ)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_setVideoBlueMute_1native
  (JNIEnv *, jclass, jint, jboolean, jboolean);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    isFreeze_native
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mediatek_tv_service_TVNative_isFreeze_1native
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    enableFreeze_native
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mediatek_tv_service_TVNative_enableFreeze_1native
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    setDisplayAspectRatio_native
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_setDisplayAspectRatio_1native
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    getDisplayAspectRatio_native
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_getDisplayAspectRatio_1native
  (JNIEnv *, jclass);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    stopStream_native
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_stopStream_1native
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    startAudioStream_native
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_startAudioStream_1native
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    syncStopVideoStream_native
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_syncStopVideoStream_1native
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    showSnowAsNoSignal_native
 * Signature: (IZ)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_showSnowAsNoSignal_1native
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    updateTVWindowRegion_native
 * Signature: (IIIII)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_updateTVWindowRegion_1native
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    updateFocusWindow_native
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_updateFocusWindow_1native
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    updateTVMode_native
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_updateTVMode_1native
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    setMTS_native
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_setMTS_1native
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    dtSetConfig_native
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_dtSetConfig_1native
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    dtSetDst_native
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_dtSetDst_1native
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    dtSetTz_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_dtSetTz_1native
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    dtSetUtc_native
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_dtSetUtc_1native
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    dtSetDstCtrl_native
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_dtSetDstCtrl_1native
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    dtSetDsChange_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_dtSetDsChange_1native
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    dtSetDsOffset_native
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_dtSetDsOffset_1native
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    dtSetSyncSrc_native
 * Signature: (IILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_dtSetSyncSrc_1native
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    dtSetTzCtrl_native
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_dtSetTzCtrl_1native
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    dtSetSysCountCode_native
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_dtSetSysCountCode_1native
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    dtGetDst_native
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mediatek_tv_service_TVNative_dtGetDst_1native
  (JNIEnv *, jclass);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    dtGetGps_native
 * Signature: ([I)J
 */
JNIEXPORT jlong JNICALL Java_com_mediatek_tv_service_TVNative_dtGetGps_1native
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    dtGetTz_native
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_mediatek_tv_service_TVNative_dtGetTz_1native
  (JNIEnv *, jclass);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    dtGetUtc_native
 * Signature: ([I)J
 */
JNIEXPORT jlong JNICALL Java_com_mediatek_tv_service_TVNative_dtGetUtc_1native
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    dtGetBrdcstUtc_native
 * Signature: ([I)J
 */
JNIEXPORT jlong JNICALL Java_com_mediatek_tv_service_TVNative_dtGetBrdcstUtc_1native
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    dtGetCountCode_native
 * Signature: (I[B[J)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_dtGetCountCode_1native
  (JNIEnv *, jclass, jint, jbyteArray, jlongArray);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    dtGetDstCtrl_native
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mediatek_tv_service_TVNative_dtGetDstCtrl_1native
  (JNIEnv *, jclass);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    dtGetDsChange_native
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_mediatek_tv_service_TVNative_dtGetDsChange_1native
  (JNIEnv *, jclass);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    dtGetDsOffset_native
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_mediatek_tv_service_TVNative_dtGetDsOffset_1native
  (JNIEnv *, jclass);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    dtGetTzCtrl_native
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mediatek_tv_service_TVNative_dtGetTzCtrl_1native
  (JNIEnv *, jclass);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    dtGetNumCountCode_native
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_dtGetNumCountCode_1native
  (JNIEnv *, jclass);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    dtGetSysCountCode_native
 * Signature: ([B[I)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_dtGetSysCountCode_1native
  (JNIEnv *, jclass, jbyteArray, jintArray);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    dtGetLastSyncTblId_native
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_com_mediatek_tv_service_TVNative_dtGetLastSyncTblId_1native
  (JNIEnv *, jclass);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    dtCheckInputTime_native
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_dtCheckInputTime_1native
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    dtConfigCheckInputTime_native
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_dtConfigCheckInputTime_1native
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    DtUtcSecToDtg_native
 * Signature: (JLcom/mediatek/tv/model/DtDTG;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_DtUtcSecToDtg_1native
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    DtUtcSecToLocDtg_native
 * Signature: (JLcom/mediatek/tv/model/DtDTG;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_DtUtcSecToLocDtg_1native
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    DtConvUtcLocal_native
 * Signature: (Lcom/mediatek/tv/model/DtDTG;Lcom/mediatek/tv/model/DtDTG;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_DtConvUtcLocal_1native
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    DtDtgToSec_native
 * Signature: (Lcom/mediatek/tv/model/DtDTG;)J
 */
JNIEXPORT jlong JNICALL Java_com_mediatek_tv_service_TVNative_DtDtgToSec_1native
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    DtGpsSecToUtcSec_native
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_mediatek_tv_service_TVNative_DtGpsSecToUtcSec_1native
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    DtBcdToSec_native
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_DtBcdToSec_1native
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    DtMjdBcdToDtg_native
 * Signature: (Ljava/lang/String;Lcom/mediatek/tv/model/DtDTG;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_DtMjdBcdToDtg_1native
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    DtMjdToDtg_native
 * Signature: (JLcom/mediatek/tv/model/DtDTG;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_DtMjdToDtg_1native
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    DtDtgToMjd_native
 * Signature: (Lcom/mediatek/tv/model/DtDTG;)J
 */
JNIEXPORT jlong JNICALL Java_com_mediatek_tv_service_TVNative_DtDtgToMjd_1native
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    DtDtgToMjdBcd_native
 * Signature: (Lcom/mediatek/tv/model/DtDTG;[I)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_DtDtgToMjdBcd_1native
  (JNIEnv *, jclass, jobject, jintArray);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    DtDiff_native
 * Signature: (Lcom/mediatek/tv/model/DtDTG;Lcom/mediatek/tv/model/DtDTG;)J
 */
JNIEXPORT jlong JNICALL Java_com_mediatek_tv_service_TVNative_DtDiff_1native
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    DtAdd_native
 * Signature: (Lcom/mediatek/tv/model/DtDTG;JLcom/mediatek/tv/model/DtDTG;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_DtAdd_1native
  (JNIEnv *, jclass, jobject, jlong, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    DtIsLeapYear_native
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mediatek_tv_service_TVNative_DtIsLeapYear_1native
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    DtRegNfyFct_native
 * Signature: ([J)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_DtRegNfyFct_1native
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    setChannelList_native
 * Signature: (IILjava/util/List;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_setChannelList_1native
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    fsSyncChannelList_native
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_fsSyncChannelList_1native
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    digitalDBClean_native
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_digitalDBClean_1native
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    fsStoreChannelList_native
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_fsStoreChannelList_1native
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    getChannelList_native
 * Signature: (ILjava/util/List;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_getChannelList_1native
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    scanServiceInit_native
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_scanServiceInit_1native
  (JNIEnv *, jclass);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    startScan_native
 * Signature: (Ljava/lang/String;Lcom/mediatek/tv/model/ScanParams;Lcom/mediatek/tv/service/ScanService;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_startScan_1native
  (JNIEnv *, jclass, jstring, jobject, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    cancelScan_native
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_cancelScan_1native
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    getScanData_native
 * Signature: (Ljava/lang/String;ILcom/mediatek/tv/model/ScanExchangeFrenquenceRange;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_getScanData_1native
  (JNIEnv *, jclass, jstring, jint, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    scanExchangeData
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_scanExchangeData
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    startScanDvbc_native
 * Signature: (Ljava/lang/String;Lcom/mediatek/tv/model/ScanParams;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_startScanDvbc_1native
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    cancelScanDvbc_native
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_cancelScanDvbc_1native
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    getDvbcScanTypeNum_native
 * Signature: (Ljava/lang/String;Lcom/mediatek/tv/model/DvbcProgramType;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_getDvbcScanTypeNum_1native
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    getDvbcFreqRange_native
 * Signature: (Ljava/lang/String;Lcom/mediatek/tv/model/DvbcFreqRange;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_getDvbcFreqRange_1native
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    getDvbcMainFrequence_native
 * Signature: (Ljava/lang/String;Lcom/mediatek/tv/model/MainFrequence;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_getDvbcMainFrequence_1native
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    getDefaultSymRate_native
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_getDefaultSymRate_1native
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    getDefaultFrequence_native
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_getDefaultFrequence_1native
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    getDefaultEMod_native
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_getDefaultEMod_1native
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    getDefaultNwID_native
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_getDefaultNwID_1native
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    startScanDtmb_native
 * Signature: (Ljava/lang/String;Lcom/mediatek/tv/model/ScanParams;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_startScanDtmb_1native
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    cancelScanDtmb_native
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_cancelScanDtmb_1native
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    getDtmbFreqRange_native
 * Signature: (Ljava/lang/String;Lcom/mediatek/tv/model/DtmbFreqRange;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_getDtmbFreqRange_1native
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    getFirstDtmbScanRF_native
 * Signature: (Ljava/lang/String;Lcom/mediatek/tv/model/DtmbScanRF;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_getFirstDtmbScanRF_1native
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    getLastDtmbScanRF_native
 * Signature: (Ljava/lang/String;Lcom/mediatek/tv/model/DtmbScanRF;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_getLastDtmbScanRF_1native
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    getNextDtmbScanRF_native
 * Signature: (Ljava/lang/String;Lcom/mediatek/tv/model/DtmbScanRF;Lcom/mediatek/tv/model/DtmbScanRF;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_getNextDtmbScanRF_1native
  (JNIEnv *, jclass, jstring, jobject, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    getPrevDtmbScanRF_native
 * Signature: (Ljava/lang/String;Lcom/mediatek/tv/model/DtmbScanRF;Lcom/mediatek/tv/model/DtmbScanRF;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_getPrevDtmbScanRF_1native
  (JNIEnv *, jclass, jstring, jobject, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    getCurrentDtmbScanRF_native
 * Signature: (Ljava/lang/String;I;Lcom/mediatek/tv/model/DtmbScanRF;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_getCurrentDtmbScanRF_1native
  (JNIEnv *, jclass, jstring, jint, jobject);


/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    inputServiceGetRecord_native
 * Signature: (ILcom/mediatek/tv/model/InputRecord;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_inputServiceGetRecord_1native
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    inputServiceBind_native
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_inputServiceBind_1native
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    inputServiceSwap_native
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_inputServiceSwap_1native
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    setScreenOutputRect_native
 * Signature: (IIIII)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_setScreenOutputRect_1native
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    setScreenOutputVideoRect_native
 * Signature: (IIIII)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_setScreenOutputVideoRect_1native
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    getScreenOutputRect_native
 * Signature: (ILcom/mediatek/tv/model/InputRegion;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_getScreenOutputRect_1native
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    getScreenOutputVideoRect_native
 * Signature: (ILcom/mediatek/tv/model/InputRegion;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_getScreenOutputVideoRect_1native
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    inputSourceExchangeData
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_inputSourceExchangeData
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    inputServiceSetOutputMute
 * Signature: (IZ)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_inputServiceSetOutputMute
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    setOSDColorKey_native
 * Signature: (ZI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mediatek_tv_service_TVNative_setOSDColorKey_1native
  (JNIEnv *, jclass, jboolean, jint);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    setOSDOpacity_native
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mediatek_tv_service_TVNative_setOSDOpacity_1native
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    eventSetCommand
 * Signature: (Lcom/mediatek/tv/model/EventCommand;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_eventSetCommand
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    getPFEvents
 * Signature: (Lcom/mediatek/tv/model/ChannelInfo;Ljava/util/List;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_getPFEvents
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    getScheduleEvents
 * Signature: (Lcom/mediatek/tv/model/ChannelInfo;JJLjava/util/List;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_getScheduleEvents
  (JNIEnv *, jclass, jobject, jlong, jlong, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    getSlotNum_native
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_getSlotNum_1native
  (JNIEnv *, jclass);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    isSlotActive_native
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mediatek_tv_service_TVNative_isSlotActive_1native
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    enterMMI_native
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_enterMMI_1native
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    getCamName_native
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mediatek_tv_service_TVNative_getCamName_1native
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    getCamSystemIDInfo_native
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_mediatek_tv_service_TVNative_getCamSystemIDInfo_1native
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    closeMMI_native
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_closeMMI_1native
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    setMMIClosed_native
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_setMMIClosed_1native
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    answerMMIMenu_native
 * Signature: (IIC)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_answerMMIMenu_1native
  (JNIEnv *, jclass, jint, jint, jchar);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    answerMMIEnq_native
 * Signature: (IIZLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_answerMMIEnq_1native
  (JNIEnv *, jclass, jint, jint, jboolean, jstring);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    askRelease_native
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_askRelease_1native
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    setCITsPath_native
 * Signature: (IZ)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_setCITsPath_1native
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    setCIInputDTVPath_native
 * Signature: (IZ)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_setCIInputDTVPath_1native
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    getTunedChannel_native
 * Signature: (ILcom/mediatek/tv/model/HostControlTune;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_getTunedChannel_1native
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    activateComponent_native
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_activateComponent_1native
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    inactivateComponent_native
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_inactivateComponent_1native
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    updateSysStatus_native
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_updateSysStatus_1native
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    IsTTXAvail_native
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mediatek_tv_service_TVNative_IsTTXAvail_1native
  (JNIEnv *, jclass);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    sendkeyEventtoComp_native
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_sendkeyEventtoComp_1native
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    lockDigitalTuner_native
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_lockDigitalTuner_1native
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    unlockDigitalTuner_native
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_unlockDigitalTuner_1native
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    getCurrentDTVAudioCodec_native
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_getCurrentDTVAudioCodec_1native
  (JNIEnv *, jclass);

/*
 * Class:     com_mediatek_tv_service_TVNative
 * Method:    getCurrentDTVVideoCodec_native
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mediatek_tv_service_TVNative_getCurrentDTVVideoCodec_1native
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
