package com.mediatek.dlna.object;

/**
 * This Class generated by browse Content object failed
 * @see com.mediatek.dlna.object.MediaServer#browse(String, com.mediatek.dlna.object.MediaServer.BrowseFlag, int, int, String, String)
 */
public class FailedContentEvent extends ContentEvent {
    /**
     *
     * @param server The action triggered by which DMS
     */
    public FailedContentEvent(MediaServer server) {
        super(server);
    }
}
