package com.mediatek.dlna.object;

import java.util.ArrayList;

/**
 * This Class generated by browse Content object successful
 * @see com.mediatek.dlna.object.MediaServer#browse(String, com.mediatek.dlna.object.MediaServer.BrowseFlag, int, int, String, String)
 */

public class NormalContentEvent extends ContentEvent {
    private int startIndex;       /* start index */
    private int requestCount;       /* request count */

    private String id;         /* the object id which browsed*/

    private int totalMatches;    /* total match in current request*/
    private int updateId;         /* the update id */

    private ArrayList<Content> list;


    /**
     *
     * @param server        Which server triggered this action
     * @param id            The object ID
     * @param startIndex    The start index in server
     * @param requestCount  How many sub object want to request
     * @param totalMatches  How many objects matched this action
     * @param updateId      The object ID
     * @param list          The content object list
     *
     * @see  com.mediatek.dlna.object.Content
     */
    public NormalContentEvent(MediaServer server, String id, int startIndex, int requestCount, int totalMatches, int updateId, ArrayList<Content> list) {
        super(server);
        this.startIndex = startIndex;
        this.requestCount = requestCount;
        this.id = id;
        this.totalMatches = totalMatches;
        this.updateId = updateId;
        this.list = list;
    }

    /**
     *
     * @return  Content object list
     */
    public ArrayList<Content> getList() {
        return list;
    }

    /**
     *
     * @return  Start index in server, begin with 0, increased by total matches
     */
    public int getStartIndex() {
        return startIndex;
    }

    /**
     *
     * @return  Request count in this action
     */
    public int getRequestCount() {
        return requestCount;
    }

    /**
     *
     * @return  The object ID
     */
    public String getId() {
        return id;
    }

    /**
     *
     * @return  Total matches in this action
     */
    public int getTotalMatches() {
        return totalMatches;
    }

    /**
     *
     * @return  The object ID
     */
    public int getUpdateId() {
        return updateId;
    }
}
