/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mediatek_dm_DeviceManager */

#ifndef _Included_com_mediatek_dm_DeviceManager
#define _Included_com_mediatek_dm_DeviceManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mediatek_dm_DeviceManager
 * Method:    nativeUmount
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_dm_DMServer_nativeUmount
  (JNIEnv *, jclass , jstring);

/*
 * Class:     com_mediatek_dm_DeviceManager
 * Method:    nativeMountISO
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_dm_DMServer_nativeMountISO
  (JNIEnv *, jclass , jstring);

/*
 * Class:     com_mediatek_dm_DeviceManager
 * Method:    nativeMountISOex
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_dm_DMServer_nativeMountISOex
 (JNIEnv *, jclass, jstring, jstring);


/*
 * Class:     com_mediatek_dm_DeviceManager
 * Method:    nativeUmountISO
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mediatek_dm_DMServer_nativeUmountISO
  (JNIEnv *, jclass , jstring);


/*
 * Class:     com_mediatek_dm_DeviceManager
 * Method:    nativeStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mediatek_dm_DMServer_nativeStart
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_mediatek_dm_DeviceManager
 * Method:    nativeEnd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mediatek_dm_DMServer_nativeEnd
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
